### PR TITLE
Add Change listener

### PR DESCRIPTION
**Pull request by jcgueriaud1**
Currently the value is changed on blur.
In my Vaadin application, I would like to trigger the change event earlier.
So this PR is adding a new event "change" that can be listened and will send the value for every changes.

### CODE REVIEW

**Comment by F0rce** [comment]
Commented on https://github.com/F0rce/ace/pull/21

**Comment by F0rce** [comment]
I added a comment to the the pull request commit you made, could you please check it before i go into further investigation?

https://github.com/jcgueriaud1/lit-ace/commit/94bffb4c140b665a1c8c096e71b1d7d25e07def7#r55124849

**Comment by jcgueriaud1** [comment]
Yes I changed it after some tests: https://github.com/F0rce/lit-ace/pull/3/files#diff-f8b960bed17b26241afc28164a3b80d0bed539b4b43eea382c78bec2a1c63feaR649

**Comment by F0rce** [comment]
Thanks for the fast answer,

Becuase this is just another "event" and it doesnt update the value, so the basic Blur Logic is not destroyed / interferred with.

I see no problem with implementing your ace and lit-ace pull requests.
I will just do some more testing. 

Have a great day,
David

**Review by F0rce — APPROVED** [review]
After multiple and increased testing, the changes are suitable for a new release

**Pull request merged**
